# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  dockerId: 'niels.pilgaard@hotmail.com'
  imageName: 'studentadministrationwebapi'
  
steps:
- task: DockerCompose@0
  inputs:
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'docker-compose up --build'
    
- script:
    docker build -t $(dockerId)/$(imageName) .
  env:
    pswd: $(dockerPassword)