# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  dockerId: 'studentadministrationsystem'
  imageName: 'studentadministrationwebapi'
  
steps:
- task: DockerCompose@0
  inputs:
    azureSubscriptionEndpoint: 'Free Trial(d33d304c-a224-4594-81f7-9e483d6e7055)'
    azureContainerRegistry: '{"loginServer":"studentadministrationsystem.azurecr.io", "id" : "/subscriptions/d33d304c-a224-4594-81f7-9e483d6e7055/resourceGroups/studentadministrationsystem/providers/Microsoft.ContainerRegistry/registries/studentadministrationsystem"}'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'build'