# ASP.NET Core


# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  dockerId: 'studentadministrationsystem'
  imageWebApi: 'studentadministrationwebapi'
  imageTest: 'studentadministrationtest'
  imageDb: 'studentadministrationdb'
  azureSubscriptionEndpoint: 'Free Trial(d33d304c-a224-4594-81f7-9e483d6e7055)'
  azureContainerRegistry: '{"loginServer":"$(dockerId).azurecr.io", "id" : "/subscriptions/d33d304c-a224-4594-81f7-9e483d6e7055/resourceGroups/$(dockerId)/providers/Microsoft.ContainerRegistry/registries/$(dockerId)"}'

steps:
- task: PowerShell@2
  inputs:
    filePath: 'init-dev-env-azure.ps1'
    
- task: Docker@1
  displayName: Container registry login
  inputs:
    command: 'login'
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)

- task: DockerCompose@0
  inputs:
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'build'

- script: |
    docker push $(dockerId).azurecr.io/$(imageWebApi)
    docker push $(dockerId).azurecr.io/$(imageTest)
    docker push $(dockerId).azurecr.io/$(imageDb)