version: '3.4'

services:
  #studentadministrationtest:
  #  image: ${DOCKER_REGISTRY-}studentadministrationtest
  #  build:
  #      context: .
  #      dockerfile: StudentAdministrationTest/Dockerfile    
  #  command: dotnet test
  #  container_name : studentadministration_test
    
  studentadministrationwebapi:
    image: ${DOCKER_REGISTRY-}studentadministrationwebapi
    build:
      context: .
      dockerfile: StudentAdministrationWebApi/Dockerfile
    restart: unless-stopped
    volumes:
      - studentadministrationdb-filestorage-volume:/app/filestorage
    container_name : studentadministration_api

  studentadministrationdb:
    image: ${DOCKER_REGISTRY-}studentadministrationdb
    build: 
      context: ./db
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
        - "3200:3306"
    environment:
        MYSQL_ROOT_PASSWORD: dkL8E6LS5UCZJjNf
        MYSQL_DATABASE: studentadministrationstore
    volumes:
        - studentadministrationdb-db-volume:/var/lib/mysql
    container_name : studentadministration_db
        
volumes:
  studentadministrationdb-db-volume:
  studentadministrationdb-filestorage-volume: