USE studentadministrationstore;
	    
CREATE TABLE IF NOT EXISTS Students (
	Id INTEGER NOT NULL AUTO_INCREMENT,
	Name VARCHAR(100) NULL DEFAULT NULL,
	Address VARCHAR(255) NULL DEFAULT NULL,
	Email VARCHAR(255) NULL DEFAULT NULL,
	PhoneNumber INT(11) NULL DEFAULT NULL,
	Historic BIT(1) NOT NULL DEFAULT b'0',
	PRIMARY KEY (Id) 
);	

CREATE TABLE IF NOT EXISTS Teachers (
	Id INTEGER NOT NULL AUTO_INCREMENT,
	Name VARCHAR(100) NULL DEFAULT NULL,
	Address VARCHAR(255) NULL DEFAULT NULL,
	Email VARCHAR(255) NULL DEFAULT NULL,
	PhoneNumber INT(11) NULL DEFAULT NULL,
	Historic BIT(1) NOT NULL DEFAULT b'0',
	PRIMARY KEY (Id) 
);
	
CREATE TABLE IF NOT EXISTS Courses (
	Id INTEGER NOT NULL AUTO_INCREMENT,
	Title VARCHAR(255) NULL DEFAULT NULL,
	Description VARCHAR(16384) NULL DEFAULT NULL,
	Historic BIT(1) NOT NULL DEFAULT b'0',
	SchoolId INTEGER NULL DEFAULT NULL,
	PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS CourseStudents (
	CourseId INT(11) NOT NULL,
	StudentId INT(11) NOT NULL,
	Score INT(11) NULL DEFAULT NULL,
	Historic BIT(1) NOT NULL DEFAULT b'0',
	PRIMARY KEY (CourseId, StudentId)
);

CREATE TABLE IF NOT EXISTS CourseTeachers (
	CourseId INT(11) NOT NULL,
	TeacherId INT(11) NOT NULL,
	Historic BIT(1) NOT NULL DEFAULT b'0',
	PRIMARY KEY (CourseId, TeacherId)
);

//TODO: Implement School