#USE studentadministrationstore;
	    
CREATE TABLE IF NOT EXISTS Student (
	Id INTEGER NOT NULL AUTO_INCREMENT,
	Name VARCHAR(100) NULL DEFAULT NULL,
	Address VARCHAR(255) NULL DEFAULT NULL,
	Email VARCHAR(255) NULL DEFAULT NULL,
	PhoneNumber INT(11) NULL DEFAULT NULL,
	Historic BIT(1) NOT NULL DEFAULT b'0',
	PRIMARY KEY (Id) 
);	

CREATE TABLE IF NOT EXISTS Teacher (
	Id INTEGER NOT NULL AUTO_INCREMENT,
	Name VARCHAR(100) NULL DEFAULT NULL,
	Address VARCHAR(255) NULL DEFAULT NULL,
	Email VARCHAR(255) NULL DEFAULT NULL,
	PhoneNumber INT(11) NULL DEFAULT NULL,
	Historic BIT(1) NOT NULL DEFAULT b'0',
	PRIMARY KEY (Id) 
);
	
CREATE TABLE IF NOT EXISTS Course (
	Id INTEGER NOT NULL AUTO_INCREMENT,
	Title VARCHAR(255) NULL DEFAULT NULL,
	Description VARCHAR(16384) NULL DEFAULT NULL,
	Historic BIT(1) NOT NULL DEFAULT b'0',
	PRIMARY KEY (Id)
);